# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        self.vboxlayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.vboxlayout.setObjectName("vboxlayout")
        self.coffee_name_edit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.coffee_name_edit.setObjectName("coffee_name_edit")
        self.vboxlayout.addWidget(self.coffee_name_edit)
        self.roast_degree_combo = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.roast_degree_combo.setObjectName("roast_degree_combo")
        self.vboxlayout.addWidget(self.roast_degree_combo)
        self.ground_or_whole_combo = QtWidgets.QComboBox(parent=AddEditCoffeeForm)
        self.ground_or_whole_combo.setObjectName("ground_or_whole_combo")
        self.vboxlayout.addWidget(self.ground_or_whole_combo)
        self.taste_desc_edit = QtWidgets.QLineEdit(parent=AddEditCoffeeForm)
        self.taste_desc_edit.setObjectName("taste_desc_edit")
        self.vboxlayout.addWidget(self.taste_desc_edit)
        self.price_spin = QtWidgets.QDoubleSpinBox(parent=AddEditCoffeeForm)
        self.price_spin.setObjectName("price_spin")
        self.vboxlayout.addWidget(self.price_spin)
        self.volume_spin = QtWidgets.QSpinBox(parent=AddEditCoffeeForm)
        self.volume_spin.setObjectName("volume_spin")
        self.vboxlayout.addWidget(self.volume_spin)
        self.save_button = QtWidgets.QPushButton(parent=AddEditCoffeeForm)
        self.save_button.setObjectName("save_button")
        self.vboxlayout.addWidget(self.save_button)

        self.retranslateUi(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        self.coffee_name_edit.setPlaceholderText(_translate("AddEditCoffeeForm", "Введите название кофе"))
        self.roast_degree_combo.setPlaceholderText(_translate("AddEditCoffeeForm", "Выберите степень обжарки"))
        self.ground_or_whole_combo.setPlaceholderText(_translate("AddEditCoffeeForm", "Выберите молотый/в зернах"))
        self.taste_desc_edit.setPlaceholderText(_translate("AddEditCoffeeForm", "Введите описание вкуса"))
        self.save_button.setText(_translate("AddEditCoffeeForm", "Сохранить"))
