# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CoffeeApp(object):
    def setupUi(self, CoffeeApp):
        CoffeeApp.setObjectName("CoffeeApp")
        CoffeeApp.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=CoffeeApp)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setObjectName("mainLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 780, 450))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.mainLayout.addWidget(self.tableWidget)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.add_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_button.setObjectName("add_button")
        self.buttonLayout.addWidget(self.add_button)
        self.edit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.edit_button.setObjectName("edit_button")
        self.buttonLayout.addWidget(self.edit_button)
        self.delete_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_button.setObjectName("delete_button")
        self.buttonLayout.addWidget(self.delete_button)
        self.mainLayout.addLayout(self.buttonLayout)
        self.label_status = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_status.setObjectName("label_status")
        self.mainLayout.addWidget(self.label_status)
        CoffeeApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(CoffeeApp)

    def retranslateUi(self, CoffeeApp):
        _translate = QtCore.QCoreApplication.translate
        CoffeeApp.setWindowTitle(_translate("CoffeeApp", "Кофейня"))
        self.add_button.setText(_translate("CoffeeApp", "Добавить кофе"))
        self.edit_button.setText(_translate("CoffeeApp", "Редактировать кофе"))
        self.delete_button.setText(_translate("CoffeeApp", "Удалить кофе"))
        self.label_status.setText(_translate("CoffeeApp", "Готово"))
